# Generated by Django 4.1.1 on 2022-09-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField()),
                ('x2', models.FloatField()),
                ('x3', models.FloatField()),
            ],
        ),
    ]
