# Generated by Django 4.1.1 on 2022-09-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba1', '0003_alter_datos_c1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='c1',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
